sudo: required

env:
    DOCKER_COMPOSE_VERSION

services:
  # Use Docker command line
  - docker

install:
  # Install dependencies for tests
  - yarn

before_script:
  # Start server and client for tests
  - npm run dev &

script:
  # Run tests
  - npm run test

deploy:
    # build docker container and push to docker-hub
    provider: script
    script: bash deploy.sh
    on:
        branch: master
