# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# eshop.blue - Production configuration
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
version: "3.7"

networks:
    eshop-network:
        driver: bridge

services:

    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                - FRONTEND_PORT=${FRONTEND_PORT:-3000}
                - FA_TOKEN=${FA_TOKEN}
                - BACKEND_API_URL=${BACKEND_API_URL}
        ports:
            - 80:80
            - 443:443
        networks:
            - eshop-network
        depends_on:
            - backend
        volumes:
            - './frontend:/app'
            - '/app/node_modules' # exclude node_modules
            - ./frontend/server/nginx.conf:/etc/nginx/nginx.conf
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root:/var/www/html
            - dhparam:/etc/ssl/certs
        restart: unless-stopped

    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
            args:
                - BACKEND_PORT=${BACKEND_PORT:-4000}
        command: '/bin/sh -c "pm2-runtime start ecosystem.config.js --env production"'
        expose:
            - ${BACKEND_PORT:-4000}
        volumes:
            - ./backend:/app
        restart: unless-stopped
        networks:
            - eshop-network

    mongo:
        container_name: mongo
        image: mongo
        environment:
            - ENV=production
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
            - MONGODB_USER=${MONGODB_USER}
            - MONGODB_PASS=${MONGODB_PASS}
        volumes:
            - ./data/db:/data/db
        expose:
            - ${MONGODB_PORT}
        command: mongod --port ${MONGODB_PORT}


    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root:/var/www/html
        depends_on:
            - frontend
        command: certonly --webroot --webroot-path=/var/www/html --email andrejn26@gmail.com --agree-tos --no-eff-email --force-renewal -d eshop.blue -d www.eshop.blue

volumes:
    certbot-etc:
    certbot-var:
    web-root:
        driver: local
        driver_opts:
            type: none
            device: /home/dev/pis-eshop/web-root/
            o: bind
    dhparam:
        driver: local
        driver_opts:
            type: none
            device: /home/dev/pis-eshop/dhparam/
            o: bind
