# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Production configuration
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
version: "3.7"

services:

    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                - FRONTEND_PORT=${FRONTEND_PORT:-3000}
                - FA_TOKEN=${FA_TOKEN}
                - BACKEND_API_URL=${BACKEND_API_URL}
        ports:
            - 80:80
            - 443:443
        links:
            - backend
        depends_on:
            - backend
        volumes:
            - './frontend:/app'
            - '/app/node_modules' # exclude node_modules
            - ./frontend/server/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/error.log:/etc/nginx/error_log.log
            - ./nginx/cache/:/etc/nginx/cache
            - /etc/letsencrypt/:/etc/letsencrypt/
        restart: always

    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
            args:
                - BACKEND_PORT=${BACKEND_PORT:-4000}
        expose:
            - ${BACKEND_PORT:-4000}
        volumes:
            - ./backend:/app
        restart: always
        privileged: true
