# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Development configuration
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
version: "3.7"

services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: 'dev-stage'
      args:
        - FRONTEND_PORT=${FRONTEND_PORT:-3000}
    ports:
      - ${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}
    volumes:
      - './frontend:/app'
      - '/app/node_modules' # exclude node_modules
    command: '/bin/sh -c "yarn run serve"'
    environment:
        - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - BACKEND_PORT=${BACKEND_PORT:-4000}
    ports:
      - ${BACKEND_PORT:-4000}:${BACKEND_PORT:-4000}
    volumes:
      - ./backend:/app
    environment:
        - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
