# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Production configuration
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
version: "3.7"

services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - FRONTEND_PORT=${FRONTEND_PORT:-3000}
    ports:
      - ${EXTERNAL_HTTP_PORT:-8080}:${FRONTEND_PORT:-3000}
    links:
      - backend
    depends_on:
      - backend
    volumes:
      - './frontend:/app'
      - '/app/node_modules' # exclude node_modules
      - './frontend/server/nginx.conf:/etc/nginx/nginx.conf'
    restart: always

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - BACKEND_PORT=${BACKEND_PORT:-4000}
    expose:
      - ${BACKEND_PORT:-4000}
    volumes:
      - ./backend:/app
    restart: always
